### ISSUE TITLE
엉뚱한 디렉토리에서 명령어를 날렸을 때 오류 처리

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#13]
`mlad-project.yml` 파일이 제대로 있지 않은 디렉토리에서 `mlad logs`, `mlad ps` 등과 같은 명령어를 입력했을 때 프로젝트가 없다, 올바른 디렉토리가 아니다 등등의 대답이 오지 않고 아래와 같은 에러 로그가 발생하여 개선이 필요합니다.

```sh
Traceback (most recent call last):
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/api/exception.py", line 50, in raise_error
    response.raise_for_status()
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://ncml-dev.cloud.ncsoft.com/api/v1/project/727b3bcbc72f5a318cc076eb2a7be3e6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/bin/mlad", line 11, in <module>
    load_entry_point('MLAppDeploy', 'console_scripts', 'mlad')()
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jooonhoe/dev/hyppo/hyppo_venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/cli/project_cli.py", line 36, in ps
    project.status(all, no_trunc)
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/cli/project.py", line 137, in status
    inspect = api.project.inspect(project_key=project_key)
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/api/project.py", line 46, in inspect
    raise_error(res)
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/api/exception.py", line 52, in raise_error
    error_from_http_errors(e)
  File "/home/jooonhoe/dev/MLAppDeploy/python/mlad/api/exception.py", line 34, in error_from_http_errors
    msg = detail['msg']
TypeError: string indices must be integers

```

**Comment by JunhoeKim** [comment]
제가 테스트한 MLAD 버전이 최신 버전이 아니었나봅니다.
다시 재현하려고 하니 에러가 발생하지 않습니다.
